### ISSUE TITLE
Deleteing shared dll

### ISSUE THREAD

**Issue by fblile** [someguy20336/TypeRight#106]
Hey Someguy, we've talked before. This is a great project.
I had an issue with Ver 3. 
Somehow its deleting a dll that is a shared project in my solution. The dll gets compiled but then it's somehow deleted when the project using it looks for it at the end of the linking. If I remove ver 3 and reinstall the ver 2 it fixes it. Install ver 3 and it does it again.
TypeRight is not being used in the shared DLL. It us only install in the main runnable project that uses the dll.
Not a crisis. Otherwise all works fantastic.
Weird problem.

**Comment by someguy20336** [comment]
Ah shoot, yea. Buildalyzer's fault. I'll unlist this package and get a fix out later. All this version did was support .NET 6 and 7 better so you aren't missing out on anything.

https://github.com/daveaglick/Buildalyzer/issues/105

**Comment by fblile** [comment]
Yep, it's a very simple solution. Two projects. The main server executable and the shared library dll.
If I build the dll first and the build the server second, it still deletes the dll.
If I set typeRight enable in the xml to false, it still deletes the dll.
I have it installed thru the Tools NuGet Package Manager
 
It did not like <SkipTypeRight>true</SkipTypeRight> in the csproj file.
 
Ill play with it some more.
 
Barry
 
 
 
-----Original Message-----

**Comment by fblile** [comment]
No hurry from me.
I truly appreciate the work you've done already.
 
Barry
 
-----Original Message-----

**Comment by someguy20336** [comment]
I believe I have a workaround for the issue.  I was able to reproduce it before the workaround so I have pretty high confidence it should work.  I deployed v3.0.1 if you want to check it out.  I unlisted 3.0.0.

Let me know if you are still having problems.

**Comment by fblile** [comment]
That fixed it!
Thank you!
 
-----Original Message-----
