### ISSUE TITLE
Net core 8

### ISSUE THREAD

**Issue by fblile** [someguy20336/TypeRight#108]
Hey Someguy, long time no problems. I really appreciate this project.
I installed .net 8 today.
TypeRight didn't work. Reinstalled it. Still didnt work. Existed with 3.
Changed in TypeRight.targets

		
		<TypeRightExe>$(MSBuildThisFileDirectory)..\..\tools\net7.0\TypeRight.exe</TypeRightExe>

The .net8 had net8.0.

No emergency for me.

**Comment by someguy20336** [comment]
Thanks for the reminder - I'll probably knock that out real quick here hopefully

**Comment by someguy20336** [comment]
added support in v3.1
