### ISSUE TITLE
Find a way that it doesn't break with every .NET release

### ISSUE THREAD

**Issue by someguy20336** [someguy20336/TypeRight#110]
Related to #108 - I made the quick fix to support .NET 8 there, but it would be nice if this tool didn't break every release.  It might be that I need to include the framework with the exe... but I remember that got obnoxiously large. Need to remember why I made a tool for each version in the first place....

Or I just update this the day of each .NET release.

**Comment by fblile** [comment]
Much appreciated!.
It's a long time between net versions.

**Comment by someguy20336** [comment]
Ok, so I just released [v3.2](https://github.com/someguy20336/TypeRight/releases/tag/v3.2.0), which should no longer break with each release.  With that, there was a big (transparent) refactoring of how the MsBuild task works in order to improve performance and simplify.  Let me know if you have any major issues with that - it seemed to work just fine with my testing, at least.
