### ISSUE TITLE
produce "fileName.js" in imports

### ISSUE THREAD

**Issue by fblile** [someguy20336/TypeRight#97]
It would really be nice to have an option to product the file name in imports with ".js" as the extension.
I saw in the code where ".ts" is removed.
This code has solved a lot of problems for me, and I really appreciate it.

**Comment by someguy20336** [comment]
sounds reasonable. 

Just to explore this idea a bit more, can you expand on your use case?  My guess is that it has to do with the [ECMA spec](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) in some way.  Are you using any tool of any sort?  Or are you just using the built in browser implementation or something and that is why you need .js?

**Comment by fblile** [comment]
Hey someguy,

I'd pay you for this as well. I'm using your stuff for free. You have a lot of work in that project.

Barry
________________________________

**Comment by someguy20336** [comment]
Thanks! That is really generous (and amazing!), but don't worry about it for now.  I don't have anything set up yet, but I might in the future.

I think an option in the config makes most sense.  Here is what I am thinking:
- New config option is `importModuleNameStyle`.  Options include: 
  - `extensionless` - current default option where extension is stripped.  
  - `replaceWithJs` - replaces the extension (likely `.ts`) with `.js`.  This sounds like what you want
    - Any import automatically pulled in will have the `.js` extension
    - Any `.ts` import you specify in the `fetchConfig/imports` option will also be replaced

What do you think about that?  Any thoughts?  Anything missing?

**Comment by fblile** [comment]
Good Morning!

What you've suggested would work perfectly for me.
I haven't used the fetch/config yet but Ill be digging in to that soon. Looks amazing.

You wrote all of this so I'm telling you something you already know.
All of this should just be built in and part of how it all works.
You've bridged the gap, literally.

Barry
________________________________

**Comment by someguy20336** [comment]
cool - I think i have what I need.  Shouldn't take too long, I don't think.

**Comment by fblile** [comment]
Good morning someGuy,

So, for some reason it stopped generating the .ts files.

It says this in the output.
2>Script generation skipped: generation in progress
2>Message while generating scripts: Script generation skipped: generation in progress

{
  // This schema is used for intellisense in visual studio
  "$schema": "https://raw.githubusercontent.com/someguy20336/TypeRight/tool/v1.4.0/TypeRight.Core/Configuration/typeRightConfig-schema.json",
  // set to "true" to enable script generation, or false to disable it
  "enabled": "true",
  // The relative path from the csproj to write the result of the default generated classes and interfaces
  "serverObjectsResultFilepath": "./TypeScript/Server/CSharpObj.ts",
  // The base url of the entire project when deployed (if running under an IIS application, for example - "/api").  This is appended
  // to the beginning of very URL
  "baseUrl": "API",
  "nameCasingConverter": "camel"
}

Not sure why.
I'm using the assembly type reference so it wouldn't generate the CSharpObj.ts as shown above.

[assembly: ScriptObjects("./TypeScript/Server/AddressObjects.ts",
   typeof(UsedOilProject.JSONConverts.AddressRoot.PersonContactSimpleJSON),
   typeof(UsedOilProject.JSONConverts.AddressRoot.AddressJSON))]

Is should product 13 .ts files with maybe 100 classes and enums.

Some feedback as it produces the ts files or as it reads the .cs files would be helpful.

What can I do to help figure out the cause?

This is such a great product I really want it to work!

Im going to keep working on it.

Barry

**Comment by someguy20336** [comment]
Dang - so it means it got stuck.  In the `obj` folder of the (most likely) web project that references the package, look for a `scriptGenLock` file and delete it.  This file is generated before build and deleted after so the MsBuild task doesn't have to duplicate the work of the extension.

If this keeps happening, let me know (maybe another issue so we can track it).  I have occasionally had it happen but I haven't been able to explain it and have just ignored it for now.

I should probably document this though in some troubleshooting guide on the wiki.  I'll to that.

Relevant code
https://github.com/someguy20336/TypeRight/blob/master/src/TypeRight.Shared/BuildHelper.cs

FYI have the feature pretty much done for this issue in #98 - still want to refactor a few things so it shouldn't be long.  I realized I have a whole bunch of dev queued up to stop supporting ASP.NET for controller actions and API calls - are you using an ASP.NET Core project?

**Comment by fblile** [comment]
yes sir, the file was there. Deleted it! All working now. Amazing!
I'm using ASPNet Core 6.

Thanks for the quick response. It's very much appreciated.

Barry
________________________________

**Comment by someguy20336** [comment]
Hey I think I finished adding the feature in #98.  Totally optional, but if you are interested in pulling the code and testing it (or at least checking out the short examples in the description of the MR) to make sure everything looks good, let me know.  I certainly don't expect it, but I just thought I would give you a chance to preview it before publishing the official NuGet package.

Otherwise, I can go ahead and merge it and deploy the next version of the package.  Can always make some small fixes in subsequent packages.

**Comment by fblile** [comment]
Fantastic! 
I’ll do it early in the morning
Very much appreciated.

**Comment by someguy20336** [comment]
Awesome, thanks!

Of course I don't have documentation on building or running the project (I'll work on that when I get a second), but hopefully you can figure it out. Running the TypeRightVsix2022 project should debug with the VS extension and you should be able to open your project and generate the scripts.

If that causes problems, the TypeRight project is the command line tool that you can provide a path to your project (might want to set the working directory to your csproj directory).

Let me know if you have problems. I'll see if I can get some instructions in the README or something today or tomorrow.

**Comment by fblile** [comment]
Yay! I got it to work.

I searched through the project and found the config-schema. I saw what to add to make it generate the .js.
I downloaded the project.

I first tried running the vsix project. I had no success. It would load my project but failed. I don't remember what the issue was.
I have zero experience making VS extensions so I was a little lost.

Next, I tried the command line project. I added the path of my project and it worked!.
I left the old version installed in my project.
I could compile from my project and the .js would disappear. Then run the command line project and the .js would reappear.

Also, from the original project, It only ever worked downloading as Nuget project thru the tools menu.

Nice job someguy!

Barry

________________________________

**Comment by someguy20336** [comment]
Great! Thanks a lot for taking the time to test it. I guess I have some documenting to do for testing it - there is a lot of magic going on right now.

I should be able to get the package published sometime today. I'll let you know if that changes, but check back tomorrow morning. It will be version 2.0.

**Comment by fblile** [comment]
Hey Someguy,
 Thank You!
________________________________

**Comment by fblile** [comment]
Fantastic!
The update worked, now on v2.

Works perfectly!

Barry
________________________________

**Comment by someguy20336** [comment]
Great to hear! Interested to hear any other ideas you might have!

Thanks for submitting an issue!

**Comment by fblile** [comment]
Good morning someguy!

I'm working with the Script Actions. I have hundreds of calls the to server. It would really help.
I starting with just a simple company data.

I'm not using Action config because the documentation says it's deprecated.

So this is what I have. I'm just showing the relevant statements.

[Area("CompanyBaseAPI")]
class CompanyBaseAPIController
HttpGet("CompanyBaseAPI/Company/{idCompany}/GetSimpleCompany")]
public async Task<ActionResult<CompanySimpleData>> GetSimpleCompany(int idCompany)
I'm NOT using [Route("api/[controller]")]
This is what it generates.
return fetchWrapper("GET", `/API/CompanyBaseAPI/CompanyBaseAPI/GetSimpleCompany/CompanyBaseAPI/Company/${idCompany}/GetSimpleCompany`, null, abort);
So, it auto generation using API/controller/controller/action/httpgetpath.

So I changed it to this.
[Area("CompanyBaseAPI")]
[Route("api/[controller]")]
class CompanyBaseAPIController
[HttpGet("Company/{idCompany}/GetSimpleCompany")]
public async Task<ActionResult<CompanySimpleData>> GetSimpleCompany(int idCompany)
This is what it generates.
return fetchWrapper("GET", `/API/api/CompanyBaseAPI/Company/${idCompany}/GetSimpleCompany`, null, abort);
so its generating API/[route]/httpgetpath

So next I tried.
[Area("CompanyBaseAPI")]
[Route("api/[controller]")]
class CompanyBaseAPIController
[HttpGet]
public async Task<ActionResult<CompanySimpleData>> GetSimpleCompany(int idCompany)
This is what it generates.
return fetchWrapper("GET", `/API/CompanyBaseAPI/CompanyBaseAPI/GetSimpleCompany`, null, abort);
so its generating [route]/controller/action.  Its missing the idCompany because it's not in the httpget.

So, If I played with what I was using to see how microsoft does it.

These both work

Without using Route
[Area("CompanyBaseAPI")]
class CompanyBaseAPIController
[HttpGet("CompanyBaseAPI/Company/{idCompany}/GetSimpleCompany")]
public async Task<ActionResult<CompanySimpleData>> GetSimpleCompany(int idCompany)works with
works with const URLAction = "/CompanyBaseAPI/Company/" + idCompany + "/GetSimpleCompany";
In this case the route in the HTTPGet is exactly what is used after the system adds https://domain stuff.

With using route
[Area("CompanyBaseAPI")]
[Route("api/[controller]")]
class CompanyBaseAPIController
[HttpGet("CompanyBaseAPI/Company/{idCompany}/GetSimpleCompany")]
public async Task<ActionResult<CompanySimpleData>> GetSimpleCompany(int idCompany)
works with const URLAction = "/API/CompanyBaseAPI/CompanyBaseAPI/Company/" + idCompany + "/GetSimpleCompany";
In this case the system adds the API/CompanyBaseAPI defined in the route to the HTTPGet path.

I prefer no route because I show API in my path anyway.
Plus, before your project, it was easier to use the no route and direct copy the HttpVerb path because it was all that was needed to copy to ts without also adding on the [Route stuff].

There's a lot here.

Barry

________________________________

**Comment by someguy20336** [comment]
Yea I would need to unpack this a bit.  Of course, I wrote this in a way that works for my use cases and we routinely use `Route` for the controller and `Http<Verb>` for each action (with the path template).  I am not sure I completely undertstand your expected route, but if this would be an example URL:

`/api/CompanyBaseApi/Company/1234/GetSimpleCompany`

Then this would be the way to set the attributes right now.  I think you are adding an extra "CompanyBaseAPI"

```csharp
[Route("api/[controller]")]
class CompanyBaseAPIController {
    [HttpGet("Company/{idCompany}/GetSimpleCompany")]
    public async Task<ActionResult<CompanySimpleData>> GetSimpleCompany(int idCompany) { }
}
```

Maybe it would be worth opening another issue with the use case you want to support?  It sounds like you don't want to add `Route` to the controller?  That might be do-able, but I would need to look into it.   Maybe a combo of seeing `Http<Verb>` but no `Route` means just use whatever is in `Http<Verb>`?  I need to read up on that again. The hard part is that I am effectively rewriting the MVC routing code, so it is tough to catch every use case or even write in the logic for "route by convention" routes.

Kind of also relates to #15 because I much prefer the `From...` attributes for parameters as well - but those in the route template should be automatically identified.

**Comment by fblile** [comment]
I’m out of town away from my computer. 
Totally support this project. 
I could be doing something wrong on my end for the routing to work the way it does. 
Microsoft does too much sometimes. 
Mine works with the straight path that’s in the http verb. It puts in the appropriate parameters. I use from body when passing in structures with put and post. 
Barry

**Comment by someguy20336** [comment]
No - you are right.  This is just a missing use case.  I should support it.  I just always use `Route` and `Http<verb>` together without "rooted" routes.  I never considered this configuration, which is totally valid.

Created #100 - can you tell me if that looks correct to you whenever you get a chance?  I think the fix is pretty small if so.  Might be able to knock it out in the next week or so and push a new package.

**Comment by fblile** [comment]
Hey someguy,

#100 looks correct to me.

I've been looking over the Net core routing.
This stuff is complicated, I feel for ya!

I steered away from the conventional routing long ago.
The httpVerb routing is so much more direct and I don't have to figure out the route to put in to the client code.
Although your project solves that!
Plus, the way I name controllers and actions doesn't always match the restful logic I'm wanting to present.
Restful paths for "gets" and such can represent different contexts but don't necessarily have different a different controller action to do the verb.

Barry
________________________________

**Comment by someguy20336** [comment]
got it fixed in #101 , will be in the next release, so look out for it.  There is one more thing I want to try to get in that release if I can, but hoping to deploy the new package in the next week or so.

**Comment by fblile** [comment]
yay!
________________________________

**Comment by fblile** [comment]
Good morning someguy!

I got the new version this morning. I can make this work.
It puts on a leading API the HTTPVerb URL.
If I put API on to my HTTPVerb path then it ends up with API/API.

So, I'm just pulling off the leading API from the URL string before the call to the server.
So it all works well for me.

I really appreciate the work you've done on this project.
Everybody using typescript and C# should be use this.

Barry
________________________________

**Comment by someguy20336** [comment]
In the config, did you configure a `baseUrl`? Sounds like you might not want that. That is intended for the IIS sub application use case. It looks like you have that based on your configuration above

**Comment by fblile** [comment]
Yes sir, you are correct!. I did have the baseURL.
Removed it and it all works perfect!.

Thank you so much.

Barry
________________________________
